# Generated by Django 6.0.1 on 2026-08-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_booking_status_event_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_company',
            name='event_img2',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event_company',
            name='event_img3',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event_company',
            name='event_img4',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
    ]
