# Generated by Django 5.2.1 on 2026-08-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_company_event_img2_event_company_event_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_company',
            name='event_img2',
        ),
        migrations.RemoveField(
            model_name='event_company',
            name='event_img3',
        ),
        migrations.RemoveField(
            model_name='event_company',
            name='event_img4',
        ),
    ]
