# Generated by Django 6.0.1 on 2026-09-07 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_backfill_events_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mob_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='package1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='package2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='package3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='package4',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event_mobile_number',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_number',
            field=models.CharField(db_column='event_mobile_number', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(db_column='event_description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(db_column='event_img', upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.BigIntegerField(db_column='event_price', default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_column='event_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='attendee',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='event_title',
            field=models.CharField(db_column='event_company_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='price',
            field=models.BigIntegerField(db_column='event_price', default=0),
        ),
    ]
