# Generated by Django 6.0.1 on 2026-09-08 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_organization'),
        ('events', '0011_remove_event_event_type_remove_event_mob_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='account_manager.organization'),
        ),
    ]
