# Generated by Django 6.1 on 2026-09-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='booking_reference',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('advance', 'Advance')], default='advance', editable=False, max_length=12)),
                ('payment_reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.eventbooking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='events_book_status_04eef5_idx')],
            },
        ),
    ]
