"""
Django settings for the Plannix project.

Plannix is a premium event planning & management platform built with Django.

Generated by 'django-admin startproject' using Django 6.0.1.
For more information, see https://docs.djangoproject.com/en/6.0/topics/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variable initialise
env = environ.Env()

# Reading .env file (values are loaded once at startup). overwrite=True makes
# .env authoritative over any pre-set shell/CI env vars (e.g. a stale
# EMAIL_HOST), so the config in .env is what actually applies.
env_path = BASE_DIR / '.env'
environ.Env.read_env(env_path, overwrite=True)
environ.Env.read_env(overwrite=True)


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])

# Cross-site request forgery — trusted origins must include the public scheme +
# host (e.g. https://plannix.onrender.com). Set in .env for production.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'themes',
    'events',
    'account_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files in production (compressed + cached with
    # far-future headers). Only enabled when USE_WHITENOISE=True and the
    # package is installed; local dev leaves it off.
    *(['whitenoise.middleware.WhiteNoiseMiddleware'] if env.bool('USE_WHITENOISE', default=False) else []),
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Plannix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Plannix.context_processors.plannix_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Plannix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Locally the app uses SQLite (default). In production set DATABASE_URL to a
# PostgreSQL connection string (e.g. the Neon pooler URL) and Django switches
# to PostgreSQL automatically — no code change needed. Example:
#   postgres://user:password@host:5432/plannix?sslmode=require
if env('DATABASE_URL', default=''):
    # Production (Neon/PostgreSQL): parse the connection string from env.
    DATABASES = {'default': env.db('DATABASE_URL')}
else:
    # Local development: SQLite, unchanged.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication URL name used by @login_required when a user is not signed in.
LOGIN_URL = 'sign_in'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

DATETIME_FORMAT = 'd M Y, h:i A'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise storage backend for compressed, cache-busted static files in
# production (requires the `whitenoise` package, only active with the flag).
if env.bool('USE_WHITENOISE', default=False):
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    WHITENOISE_AUTOREFRESH = env.bool('WHITENOISE_AUTOREFRESH', default=True)
    WHITENOISE_MAX_AGE = 31536000  # 1 year for immutable hashed assets

# Cloudinary media storage — optional, enabled via .env for production.
# Requires `cloudinary` and `django-cloudinary-storage` (not installed locally;
# this block only activates when USE_CLOUDINARY=True and the keys are set).
# Evaluated after WhiteNoise so STORAGES['default'] correctly overrides to
# Cloudinary media storage when both flags are active.
if env.bool('USE_CLOUDINARY', default=False):
    INSTALLED_APPS = INSTALLED_APPS + [
        'cloudinary_storage',
        'cloudinary',
    ]
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default=''),
        'API_KEY': env('CLOUDINARY_API_KEY', default=''),
        'API_SECRET': env('CLOUDINARY_API_SECRET', default=''),
    }
    STORAGES['default'] = {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'}


# E-mail configuration
# The app password lives in .env; credentials are never committed.
# Backend defaults to the console backend for local development (emails print
# to the terminal). To send real mail, set EMAIL_BACKEND to the SMTP backend in
# .env — e.g. django.core.mail.backends.smtp.EmailBackend for Gmail.
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
SERVER_EMAIL = env('SERVER_EMAIL', default=EMAIL_HOST_USER)
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
# Default sender for all app emails; falls back to EMAIL_HOST_USER when unset.
DEFAULT_FROM_EMAIL = env(
    'DEFAULT_FROM_EMAIL',
    default=EMAIL_HOST_USER or 'plannix@example.com',
)


# Advance payment (Razorpay) — keys come from env; empty in local dev means the
# payment gateway is unavailable (the "Pay Advance" action stays hidden).
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', default='')
# Percentage of the package price collected as the advance. Server-calculated
# and never trusted from the browser.
PAYMENT_ADVANCE_PERCENT = env.int('PAYMENT_ADVANCE_PERCENT', default=30)


# Session timeout configuration (django-session-timeout)
SESSION_EXPIRE_SECONDS = 1800  # Expire after 30 minutes
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = 'sign_in'  # URL name to redirect to on session timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Invalid session after browser is closed

# Session security hardening
SESSION_COOKIE_HTTPONLY = True   # JavaScript cannot access session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF cross-site protection
CSRF_COOKIE_HTTPONLY = True      # JavaScript cannot access CSRF cookie

# HTTPS settings — enabled via .env behind TLS in production, off by default
# so local development over HTTP keeps working unchanged.
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)

# HSTS settings
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)

# XSS & content-type protections
SECURE_BROWSER_XSS_FILTER = env.bool('SECURE_BROWSER_XSS_FILTER', default=True)
SECURE_CONTENT_TYPE_NOSNIFF = env.bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)

# Connection keep-alive / request timeout guard for the mail backend (seconds).
# Prevents a slow or unreachable SMTP server from hanging a booking request.
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=15)


# Message tags mapped to Bootstrap 5 alert classes
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}


# Jazzmin — Plannix-branded Django administration
JAZZMIN_SETTINGS = {
    'site_title': 'Plannix Admin',
    'site_header': 'Plannix',
    'site_brand': 'Plannix Admin',
    'site_logo': 'img/plannix-mark.png',
    'site_logo_classes': 'img-circle',
    'site_icon': 'img/favicon-32x32.png',
    'welcome_sign': 'Welcome to the Plannix administration panel',
    'copyright': 'Plannix',
    'show_sidebar': True,
    'navigation_expanded': True,
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.User': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'events.Event': 'fas fa-calendar-check',
        'events.EventCategory': 'fas fa-tags',
        'events.EventInclusion': 'fas fa-list-check',
        'events.EventImage': 'fas fa-images',
        'events.EventBooking': 'fas fa-ticket-alt',
        'events.Review': 'fas fa-star',
        'events.EventAuditLog': 'fas fa-clock-rotate-left',
        'account_manager.OrganizerProfile': 'fas fa-id-badge',
        'themes.Feedback': 'fas fa-comment-dots',
    },
    'order_with_respect_to': ['events', 'themes', 'auth'],
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': True,
    'brand_small_text': False,
    'brand_colour': 'navbar-dark',
    'accent': 'accent-primary',
    'navbar': 'navbar-dark',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': False,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': True,
    'theme': 'cosmo',
    'dark_mode_theme': 'darkly',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}
